# Advanced optional Bayesian workflows for gp3bayes
#
# This file is generated by gp3bayes_advanced_extension_installer.R.
# The functions remain optional, conservative adapters around established
# Bayesian packages. They do not provide automatic model selection, automatic
# adequacy claims, causal interpretation, or unrestricted formulas/families.

.gp3x_stop <- function(...) {
  stop(paste0(...), call. = FALSE)
}

.gp3x_require <- function(package, purpose) {
  if (!requireNamespace(package, quietly = TRUE)) {
    .gp3x_stop(
      "Optional package `", package, "` is required to ", purpose, "."
    )
  }
  invisible(TRUE)
}

.gp3x_scalar_integer <- function(x, name, minimum = 0L) {
  if (!is.numeric(x) || length(x) != 1L || is.na(x) ||
      !is.finite(x) || x != floor(x) || x < minimum) {
    .gp3x_stop("`", name, "` must be one integer >= ", minimum, ".")
  }
  as.integer(x)
}

.gp3x_scalar_number <- function(
  x,
  name,
  lower = -Inf,
  upper = Inf,
  lower_open = FALSE,
  upper_open = FALSE
) {
  if (!is.numeric(x) || length(x) != 1L || is.na(x) || !is.finite(x)) {
    .gp3x_stop("`", name, "` must be one finite numeric value.")
  }
  lower_ok <- if (lower_open) x > lower else x >= lower
  upper_ok <- if (upper_open) x < upper else x <= upper
  if (!lower_ok || !upper_ok) {
    .gp3x_stop("`", name, "` is outside the permitted interval.")
  }
  as.numeric(x)
}

.gp3x_unwrap_fit <- function(x) {
  if (inherits(x, "gp3bayes_fit")) {
    return(x$backend_fit)
  }
  if (inherits(x, "brmsfit")) {
    return(x)
  }
  .gp3x_stop(
    "`x` must be a gp3bayes fit or a `brmsfit` object."
  )
}

.gp3x_call_supported <- function(fun, args) {
  formal_names <- names(formals(fun))
  if (!"..." %in% formal_names) {
    args <- args[names(args) %in% formal_names]
  }
  do.call(fun, args)
}

.gp3x_backend_version <- function(package) {
  if (!requireNamespace(package, quietly = TRUE)) {
    return(NA_character_)
  }
  as.character(utils::packageVersion(package))
}

.gp3x_interaction_coef <- function(translation) {
  prior_table <- brms::get_prior(
    formula = translation$formula,
    data = translation$specification$prepared$data,
    family = translation$family_object
  )
  prior_table <- as.data.frame(prior_table, stringsAsFactors = FALSE)

  candidates <- prior_table$coef[
    prior_table$class == "b" &
      !is.na(prior_table$coef) &
      nzchar(prior_table$coef) &
      grepl(":", prior_table$coef, fixed = TRUE)
  ]
  candidates <- unique(candidates)

  if (length(candidates) != 1L) {
    .gp3x_stop(
      "The approved specification must contain exactly one identifiable ",
      "two-way interaction coefficient; found ", length(candidates), "."
    )
  }
  candidates[[1L]]
}

.gp3x_apply_interaction_prior <- function(
  translation,
  scale,
  tag = "interaction"
) {
  .gp3x_require("brms", "translate a coefficient-specific interaction prior")
  scale <- .gp3x_scalar_number(
    scale, "interaction_scale", lower = 0, lower_open = TRUE
  )

  coef_name <- .gp3x_interaction_coef(translation)
  prior_text <- paste0("normal(0, ", format(scale, trim = TRUE), ")")

  interaction_prior <- brms::set_prior(
    prior = prior_text,
    class = "b",
    coef = coef_name,
    tag = tag
  )

  translated_priors <- c(translation$priors, interaction_prior)
  validated <- brms::validate_prior(
    prior = translated_priors,
    formula = translation$formula,
    data = translation$specification$prepared$data,
    family = translation$family_object
  )

  table <- as.data.frame(validated, stringsAsFactors = FALSE)
  matched <- table$class == "b" &
    table$coef == coef_name &
    table$source == "user"

  if (!any(matched)) {
    .gp3x_stop(
      "The coefficient-specific interaction prior was not retained by brms."
    )
  }

  translation$priors <- translated_priors
  translation$validated_priors <- validated
  translation$parameter_table <- table
  translation$prior_text <- c(
    translation$prior_text,
    interaction = prior_text
  )
  translation$interaction_prior <- list(
    coefficient = coef_name,
    scale = scale,
    prior = prior_text,
    tag = tag
  )
  translation$translation_version <- "0.2"
  translation
}

#' Report Optional Bayesian Backend Capabilities
#'
#' Audits package availability and, where possible, runtime usability for the
#' optional Bayesian extensions.
#'
#' @return A `gp3bayes_backend_capabilities` data frame.
#' @export
bayesian_backend_capabilities <- function() {
  packages <- c(
    "brms", "rstan", "cmdstanr", "loo",
    "priorsense", "detectseparation", "SBC"
  )

  installed <- vapply(
    packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1L)
  )

  versions <- vapply(
    packages,
    .gp3x_backend_version,
    FUN.VALUE = character(1L)
  )

  usable <- installed
  detail <- ifelse(installed, "package available", "package not installed")

  cmd_index <- match("cmdstanr", packages)
  if (installed[[cmd_index]]) {
    cmd_check <- tryCatch(
      {
        cmdstanr::check_cmdstan_toolchain(quiet = TRUE)
        path <- cmdstanr::cmdstan_path()
        version <- as.character(cmdstanr::cmdstan_version())
        list(
          usable = nzchar(path),
          detail = paste0("CmdStan ", version, " at ", path)
        )
      },
      error = function(e) {
        list(usable = FALSE, detail = conditionMessage(e))
      }
    )
    usable[[cmd_index]] <- cmd_check$usable
    detail[[cmd_index]] <- cmd_check$detail
  }

  result <- data.frame(
    component = packages,
    installed = unname(installed),
    version = unname(versions),
    usable = unname(usable),
    detail = unname(detail),
    stringsAsFactors = FALSE
  )

  structure(
    result,
    class = c("gp3bayes_backend_capabilities", "data.frame")
  )
}

#' @export
print.gp3bayes_backend_capabilities <- function(x, ...) {
  cat("\nOptional Bayesian capabilities\n\n")
  print.data.frame(x, row.names = FALSE)
  invisible(x)
}

#' Check the CmdStanR Backend
#'
#' Checks package availability, the C++ toolchain, and a configured CmdStan
#' installation. No installation or repair is performed automatically.
#'
#' @param strict Whether to stop instead of returning a failed audit.
#'
#' @return A list with status, version, path, and diagnostic detail.
#' @export
check_cmdstan_backend <- function(strict = FALSE) {
  if (!is.logical(strict) || length(strict) != 1L || is.na(strict)) {
    .gp3x_stop("`strict` must be TRUE or FALSE.")
  }

  result <- tryCatch(
    {
      .gp3x_require("cmdstanr", "check the CmdStan backend")
      cmdstanr::check_cmdstan_toolchain(quiet = TRUE)
      path <- cmdstanr::cmdstan_path()
      version <- as.character(cmdstanr::cmdstan_version())
      list(
        status = "pass",
        usable = TRUE,
        path = path,
        version = version,
        detail = "CmdStanR, the toolchain, and CmdStan are available."
      )
    },
    error = function(e) {
      list(
        status = "fail",
        usable = FALSE,
        path = NA_character_,
        version = NA_character_,
        detail = conditionMessage(e)
      )
    }
  )

  class(result) <- "gp3bayes_cmdstan_backend_audit"

  if (strict && !isTRUE(result$usable)) {
    .gp3x_stop("CmdStan backend audit failed: ", result$detail)
  }
  result
}

#' @export
print.gp3bayes_cmdstan_backend_audit <- function(x, ...) {
  cat("\nCmdStan backend audit\n")
  cat(" Status: ", x$status, "\n", sep = "")
  cat(" Usable: ", x$usable, "\n", sep = "")
  if (!is.na(x$version)) {
    cat(" Version: ", x$version, "\n", sep = "")
  }
  if (!is.na(x$path)) {
    cat(" Path: ", x$path, "\n", sep = "")
  }
  cat(" Detail: ", x$detail, "\n", sep = "")
  invisible(x)
}

#' Specify a Binary Model with a Separate Interaction Prior
#'
#' Retains the approved binary model contract while recording a common
#' main-effect prior scale and a narrower coefficient-specific interaction
#' prior scale.
#'
#' @param prepared A `gp3bayes_binary_prepared` object containing one approved
#'   two-way interaction.
#' @param baseline Plausible baseline event probability.
#' @param intercept_scale Intercept-prior scale.
#' @param main_effect_scale Common population main-effect prior scale.
#' @param interaction_scale Interaction prior scale.
#' @param group_sd_scale Group-level standard-deviation prior scale.
#' @param correlation_eta LKJ shape.
#' @param student_df Student-t degrees of freedom.
#'
#' @return A binary model specification with advanced prior metadata.
#' @export
specify_binary_model_with_interaction_prior <- function(
  prepared,
  baseline,
  intercept_scale = 1.5,
  main_effect_scale = 0.75,
  interaction_scale = 0.50,
  group_sd_scale = 1,
  correlation_eta = 2,
  student_df = 3
) {
  if (!inherits(prepared, "gp3bayes_binary_prepared")) {
    .gp3x_stop("`prepared` must be a binary prepared object.")
  }
  if (is.null(prepared$contract$interaction)) {
    .gp3x_stop(
      "A declared two-way interaction is required for this specification."
    )
  }

  specification <- specify_binary_model(
    prepared = prepared,
    baseline = baseline,
    intercept_scale = intercept_scale,
    coefficient_scale = main_effect_scale,
    group_sd_scale = group_sd_scale,
    correlation_eta = correlation_eta,
    student_df = student_df
  )

  specification$advanced_priors <- list(
    main_effect_scale = .gp3x_scalar_number(
      main_effect_scale, "main_effect_scale", 0, lower_open = TRUE
    ),
    interaction_scale = .gp3x_scalar_number(
      interaction_scale, "interaction_scale", 0, lower_open = TRUE
    ),
    interaction = prepared$contract$interaction,
    interaction_tag = "interaction"
  )
  specification$advanced_prior_version <- "0.2"

  class(specification) <- c(
    "gp3bayes_binary_interaction_prior_specification",
    class(specification)
  )
  specification
}

#' Specify a Duration Model with a Separate Interaction Prior
#'
#' Uses the candidate duration defaults of 0.35 for population main effects
#' and 0.25 for the approved two-way interaction.
#'
#' @inheritParams specify_binary_model_with_interaction_prior
#' @param baseline Plausible baseline median in the recorded outcome unit.
#' @param main_effect_scale Common population main-effect prior scale.
#' @param interaction_scale Interaction prior scale.
#' @param residual_scale Lognormal residual-scale prior scale.
#'
#' @return A duration model specification with advanced prior metadata.
#' @export
specify_duration_model_with_interaction_prior <- function(
  prepared,
  baseline,
  intercept_scale = 1,
  main_effect_scale = 0.35,
  interaction_scale = 0.25,
  group_sd_scale = 0.5,
  residual_scale = 0.5,
  correlation_eta = 2,
  student_df = 3
) {
  if (!inherits(prepared, "gp3bayes_duration_prepared")) {
    .gp3x_stop("`prepared` must be a duration prepared object.")
  }
  if (is.null(prepared$contract$interaction)) {
    .gp3x_stop(
      "A declared two-way interaction is required for this specification."
    )
  }

  specification <- specify_duration_model(
    prepared = prepared,
    baseline = baseline,
    intercept_scale = intercept_scale,
    coefficient_scale = main_effect_scale,
    group_sd_scale = group_sd_scale,
    residual_scale = residual_scale,
    correlation_eta = correlation_eta,
    student_df = student_df
  )

  specification$advanced_priors <- list(
    main_effect_scale = .gp3x_scalar_number(
      main_effect_scale, "main_effect_scale", 0, lower_open = TRUE
    ),
    interaction_scale = .gp3x_scalar_number(
      interaction_scale, "interaction_scale", 0, lower_open = TRUE
    ),
    interaction = prepared$contract$interaction,
    interaction_tag = "interaction"
  )
  specification$advanced_prior_version <- "0.2"

  class(specification) <- c(
    "gp3bayes_duration_interaction_prior_specification",
    class(specification)
  )
  specification
}

#' Summarise Separate Interaction Prior Metadata
#'
#' @param specification An advanced binary or duration specification.
#'
#' @return A one-row data frame.
#' @export
interaction_prior_summary <- function(specification) {
  metadata <- specification$advanced_priors
  if (is.null(metadata)) {
    .gp3x_stop(
      "`specification` does not contain separate interaction-prior metadata."
    )
  }

  data.frame(
    family = specification$family,
    interaction = paste(metadata$interaction, collapse = ":"),
    main_effect_scale = metadata$main_effect_scale,
    interaction_scale = metadata$interaction_scale,
    interaction_tag = metadata$interaction_tag,
    stringsAsFactors = FALSE
  )
}

#' Translate an Advanced Binary Specification to brms
#'
#' @param specification An advanced binary specification.
#'
#' @return A validated restricted brms translation.
#' @export
translate_binary_model_with_interaction_prior <- function(specification) {
  if (!inherits(
    specification,
    "gp3bayes_binary_interaction_prior_specification"
  )) {
    .gp3x_stop(
      "`specification` must be created by ",
      "`specify_binary_model_with_interaction_prior()`."
    )
  }

  translation <- translate_binary_model_to_brms(specification)
  translation <- .gp3x_apply_interaction_prior(
    translation,
    specification$advanced_priors$interaction_scale,
    tag = specification$advanced_priors$interaction_tag
  )
  class(translation) <- c(
    "gp3bayes_binary_advanced_backend_specification",
    class(translation)
  )
  translation
}

#' Translate an Advanced Duration Specification to brms
#'
#' @param specification An advanced duration specification.
#'
#' @return A validated restricted brms translation.
#' @export
translate_duration_model_with_interaction_prior <- function(specification) {
  if (!inherits(
    specification,
    "gp3bayes_duration_interaction_prior_specification"
  )) {
    .gp3x_stop(
      "`specification` must be created by ",
      "`specify_duration_model_with_interaction_prior()`."
    )
  }

  translation <- translate_duration_model_to_brms(specification)
  translation <- .gp3x_apply_interaction_prior(
    translation,
    specification$advanced_priors$interaction_scale,
    tag = specification$advanced_priors$interaction_tag
  )
  class(translation) <- c(
    "gp3bayes_duration_advanced_backend_specification",
    class(translation)
  )
  translation
}

.gp3x_translate_for_backend <- function(specification) {
  if (inherits(
    specification,
    "gp3bayes_binary_interaction_prior_specification"
  )) {
    return(translate_binary_model_with_interaction_prior(specification))
  }
  if (inherits(
    specification,
    "gp3bayes_duration_interaction_prior_specification"
  )) {
    return(translate_duration_model_with_interaction_prior(specification))
  }
  if (inherits(specification, "gp3bayes_binary_model_specification")) {
    return(translate_binary_model_to_brms(specification))
  }
  if (inherits(specification, "gp3bayes_duration_model_specification")) {
    return(translate_duration_model_to_brms(specification))
  }
  .gp3x_stop("Unsupported specification class.")
}

.gp3x_fit_backend <- function(
  specification,
  backend,
  chains,
  iter,
  warmup,
  cores,
  seed,
  adapt_delta,
  max_treedepth,
  refresh
) {
  backend <- match.arg(backend, c("rstan", "cmdstanr"))
  chains <- .gp3x_scalar_integer(chains, "chains", 1L)
  iter <- .gp3x_scalar_integer(iter, "iter", 100L)
  warmup <- .gp3x_scalar_integer(warmup, "warmup", 0L)
  cores <- .gp3x_scalar_integer(cores, "cores", 1L)
  seed <- .gp3x_scalar_integer(seed, "seed", 0L)
  max_treedepth <- .gp3x_scalar_integer(
    max_treedepth, "max_treedepth", 5L
  )
  refresh <- .gp3x_scalar_integer(refresh, "refresh", 0L)
  adapt_delta <- .gp3x_scalar_number(
    adapt_delta,
    "adapt_delta",
    lower = 0,
    upper = 1,
    lower_open = TRUE,
    upper_open = TRUE
  )

  if (warmup >= iter) {
    .gp3x_stop("`warmup` must be smaller than `iter`.")
  }
  if (cores > chains) {
    .gp3x_stop("`cores` cannot exceed `chains`.")
  }

  .gp3x_require("brms", "fit an advanced gp3bayes model")
  if (identical(backend, "rstan")) {
    .gp3x_require("rstan", "use the rstan sampling backend")
  } else {
    check_cmdstan_backend(strict = TRUE)
  }

  translation <- .gp3x_translate_for_backend(specification)

  backend_fit <- brms::brm(
    formula = translation$formula,
    data = specification$prepared$data,
    family = translation$family_object,
    prior = translation$priors,
    backend = backend,
    algorithm = "sampling",
    sample_prior = "no",
    save_pars = brms::save_pars(all = TRUE),
    chains = chains,
    iter = iter,
    warmup = warmup,
    cores = cores,
    seed = seed,
    control = list(
      adapt_delta = adapt_delta,
      max_treedepth = max_treedepth
    ),
    refresh = refresh
  )

  family <- specification$family
  family_class <- if (identical(family, "binary")) {
    "gp3bayes_binary_fit"
  } else {
    "gp3bayes_duration_fit"
  }

  versions <- c(
    brms = .gp3x_backend_version("brms"),
    backend = .gp3x_backend_version(backend)
  )
  names(versions)[[2L]] <- backend

  result <- list(
    fit_version = "0.2",
    family = family,
    model_family = specification$model_family,
    specification = specification,
    translation = translation,
    backend_fit = backend_fit,
    outcome_unit = specification$outcome_unit %||% NULL,
    backend_interface = "brms",
    sampling_backend = backend,
    algorithm = "sampling",
    sampling = list(
      chains = chains,
      iter = iter,
      warmup = warmup,
      post_warmup_iterations = iter - warmup,
      cores = cores,
      seed = seed,
      adapt_delta = adapt_delta,
      max_treedepth = max_treedepth,
      refresh = refresh
    ),
    package_versions = versions,
    unrestricted_formula = FALSE,
    fit_performed = TRUE,
    diagnostics_assessed = FALSE,
    posterior_adequacy_established = FALSE
  )

  structure(
    result,
    class = c(
      "gp3bayes_backend_portable_fit",
      family_class,
      "gp3bayes_fit"
    )
  )
}

`%||%` <- function(x, y) {
  if (is.null(x)) y else x
}

#' Fit a Binary Model with a Selected Full-MCMC Backend
#'
#' The formula and family remain contract-restricted. The only selectable
#' implementation detail is whether brms delegates full MCMC sampling to
#' rstan or CmdStanR.
#'
#' @param specification An approved binary model specification.
#' @param backend Either `"rstan"` or `"cmdstanr"`.
#' @param chains Number of chains.
#' @param iter Total iterations per chain.
#' @param warmup Warmup iterations per chain.
#' @param cores Number of cores, not exceeding chains.
#' @param seed Non-negative integer seed.
#' @param adapt_delta NUTS target acceptance probability.
#' @param max_treedepth NUTS maximum tree depth.
#' @param refresh Progress refresh interval.
#'
#' @return A `gp3bayes_backend_portable_fit`.
#' @export
fit_binary_model_backend <- function(
  specification,
  backend = c("rstan", "cmdstanr"),
  chains = 4L,
  iter = 2000L,
  warmup = 1000L,
  cores = .gp3b_default_cores(chains),
  seed = 1L,
  adapt_delta = 0.95,
  max_treedepth = 12L,
  refresh = 0L
) {
  if (!inherits(specification, "gp3bayes_binary_model_specification")) {
    .gp3x_stop("`specification` must be an approved binary specification.")
  }
  .gp3x_fit_backend(
    specification = specification,
    backend = match.arg(backend),
    chains = chains,
    iter = iter,
    warmup = warmup,
    cores = cores,
    seed = seed,
    adapt_delta = adapt_delta,
    max_treedepth = max_treedepth,
    refresh = refresh
  )
}

#' Fit a Duration Model with a Selected Full-MCMC Backend
#'
#' @inheritParams fit_binary_model_backend
#' @param specification An approved duration model specification.
#'
#' @return A `gp3bayes_backend_portable_fit`.
#' @export
fit_duration_model_backend <- function(
  specification,
  backend = c("rstan", "cmdstanr"),
  chains = 4L,
  iter = 2000L,
  warmup = 1000L,
  cores = .gp3b_default_cores(chains),
  seed = 1L,
  adapt_delta = 0.95,
  max_treedepth = 12L,
  refresh = 0L
) {
  if (!inherits(specification, "gp3bayes_duration_model_specification")) {
    .gp3x_stop("`specification` must be an approved duration specification.")
  }
  .gp3x_fit_backend(
    specification = specification,
    backend = match.arg(backend),
    chains = chains,
    iter = iter,
    warmup = warmup,
    cores = cores,
    seed = seed,
    adapt_delta = adapt_delta,
    max_treedepth = max_treedepth,
    refresh = refresh
  )
}

#' @rdname fit_binary_model_backend
#' @export
fit_binary_model_cmdstanr <- function(
  specification,
  chains = 4L,
  iter = 2000L,
  warmup = 1000L,
  cores = .gp3b_default_cores(chains),
  seed = 1L,
  adapt_delta = 0.95,
  max_treedepth = 12L,
  refresh = 0L
) {
  fit_binary_model_backend(
    specification = specification,
    backend = "cmdstanr",
    chains = chains,
    iter = iter,
    warmup = warmup,
    cores = cores,
    seed = seed,
    adapt_delta = adapt_delta,
    max_treedepth = max_treedepth,
    refresh = refresh
  )
}

#' @rdname fit_duration_model_backend
#' @export
fit_duration_model_cmdstanr <- function(
  specification,
  chains = 4L,
  iter = 2000L,
  warmup = 1000L,
  cores = .gp3b_default_cores(chains),
  seed = 1L,
  adapt_delta = 0.95,
  max_treedepth = 12L,
  refresh = 0L
) {
  fit_duration_model_backend(
    specification = specification,
    backend = "cmdstanr",
    chains = chains,
    iter = iter,
    warmup = warmup,
    cores = cores,
    seed = seed,
    adapt_delta = adapt_delta,
    max_treedepth = max_treedepth,
    refresh = refresh
  )
}

#' @export
print.gp3bayes_backend_portable_fit <- function(x, ...) {
  cat("\nBackend-portable gp3bayes fit\n")
  cat(" Family: ", x$family, "\n", sep = "")
  cat(" Formula: ", x$translation$formula_text, "\n", sep = "")
  cat(" Interface: brms\n")
  cat(" Sampling backend: ", x$sampling_backend, "\n", sep = "")
  cat(" Algorithm: full MCMC sampling\n")
  cat(" Chains: ", x$sampling$chains, "\n", sep = "")
  cat(" Iterations per chain: ", x$sampling$iter, "\n", sep = "")
  cat(" Diagnostics assessed: FALSE\n")
  cat(" Posterior adequacy established: FALSE\n")
  invisible(x)
}

#' Detect Separation in the Binary Fixed-Effects Screen
#'
#' Runs `detectseparation::detect_separation()` as a pre-fit fixed-effects
#' screen. This screen does not replace the hierarchical model or prove that
#' the Bayesian posterior is adequate.
#'
#' @param x An approved binary specification, or a data frame when `formula`
#'   is supplied.
#' @param formula Optional fixed-effects binomial formula.
#' @param data Optional data frame. It overrides data extracted from `x`.
#'
#' @return A `gp3bayes_separation_screen`.
#' @export
detect_binary_separation <- function(x, formula = NULL, data = NULL) {
  .gp3x_require(
    "detectseparation",
    "screen a binary fixed-effects design for separation"
  )

  specification_input <- inherits(
    x,
    "gp3bayes_binary_model_specification"
  )

  if (specification_input) {
    if (is.null(data)) {
      data <- x$prepared$data
    }

    if (is.null(formula)) {
      formula <- x$fixed_formula
    }

    if (is.null(formula) && !is.null(x$prepared$fixed_formula)) {
      formula <- x$prepared$fixed_formula
    }

  } else if (is.data.frame(x)) {
    if (is.null(data)) {
      data <- x
    }

  } else {
    .gp3x_stop(
      "`x` must be an approved binary specification or a data frame."
    )
  }

  if (!inherits(formula, "formula")) {
    .gp3x_stop(
      "`formula` must be supplied as a formula."
    )
  }

  if (!is.data.frame(data)) {
    .gp3x_stop(
      "`data` must be a data frame."
    )
  }

  response_name <- all.vars(formula[[2L]])

  if (
    length(response_name) != 1L ||
    !response_name %in% names(data)
  ) {
    .gp3x_stop(
      "The separation-screen response must identify one column in `data`."
    )
  }

  response <- data[[response_name]]

  valid_binary <- all(
    stats::na.omit(response) %in% c(0, 1, FALSE, TRUE)
  )

  if (!valid_binary) {
    .gp3x_stop(
      "The separation-screen outcome must be binary."
    )
  }

  screen <- stats::glm(
    formula = formula,
    data = data,
    family = stats::binomial(link = "logit"),
    method = detectseparation::detect_separation
  )

  coefficients_raw <- stats::coef(screen)

  coefficient_names <- names(coefficients_raw)

  coefficients <- as.numeric(coefficients_raw)

  names(coefficients) <- coefficient_names

  infinite <- is.infinite(coefficients)
  separated <- any(infinite)

  coefficient_table <- data.frame(
    coefficient = names(coefficients),
    separation_code = unname(coefficients),
    infinite = unname(infinite),
    direction = ifelse(
      coefficients == Inf,
      "positive_infinity",
      ifelse(
        coefficients == -Inf,
        "negative_infinity",
        "finite"
      )
    ),
    stringsAsFactors = FALSE
  )

  structure(
    list(
      status = if (separated) "review" else "pass",
      separation_detected = separated,
      coefficients = coefficient_table,
      formula = formula,
      n_observations = nrow(data),
      raw = screen,
      screening_only = TRUE,
      interpretation = paste(
        "This is a fixed-effects logistic separation screen.",
        "Grouping terms from the hierarchical specification are not",
        "included in this screening GLM.",
        "The screen neither fits nor validates the hierarchical",
        "Bayesian model."
      )
    ),
    class = "gp3bayes_separation_screen"
  )
}
#' @export
print.gp3bayes_separation_screen <- function(x, ...) {
  cat("\nBinary separation screen\n")
  cat(" Status: ", x$status, "\n", sep = "")
  cat(" Separation detected: ", x$separation_detected, "\n", sep = "")
  cat(" Observations: ", x$n_observations, "\n", sep = "")
  print(x$coefficients, row.names = FALSE)
  cat("\n", x$interpretation, "\n", sep = "")
  invisible(x)
}

#' @method plot gp3bayes_separation_screen
#' @export
plot.gp3bayes_separation_screen <- function(
    x,
    main = "Fixed-effects separation screen",
    ...
) {
  if (!inherits(x, "gp3bayes_separation_screen")) {
    .gp3x_stop(
      "`x` must be a `gp3bayes_separation_screen` object."
    )
  }

  codes <- as.numeric(
    unlist(
      x$coefficients[["separation_code"]],
      use.names = FALSE
    )
  )

  coefficient_names <- as.character(
    x$coefficients[["coefficient"]]
  )

  if (
    length(codes) == 0L ||
    length(codes) != length(coefficient_names) ||
    anyNA(codes)
  ) {
    .gp3x_stop(
      "The separation coefficient table cannot be plotted."
    )
  }

  display_codes <- ifelse(
    is.infinite(codes),
    sign(codes),
    0
  )

  graphics::barplot(
    height = display_codes,
    names.arg = coefficient_names,
    las = 2,
    ylim = c(-1.2, 1.2),
    ylab = "-1: -Inf, 0: finite, 1: +Inf",
    main = main,
    ...
  )

  graphics::abline(
    h = 0,
    lty = 2
  )

  invisible(x)
}


.gp3x_wrap_loo <- function(raw, source = NULL) {
  .gp3x_require("loo", "summarise PSIS-LOO diagnostics")

  if (!inherits(raw, "loo")) {
    .gp3x_stop(
      "`raw` must be a `loo` object."
    )
  }

  pareto_k <- loo::pareto_k_values(raw)

  if (!is.numeric(pareto_k)) {
    pareto_k <- as.numeric(pareto_k)
  }

  flagged <- loo::pareto_k_ids(raw)

  if (is.null(flagged)) {
    flagged <- integer()
  }

  flagged <- as.integer(flagged)

  severe <- which(
    is.finite(pareto_k) & pareto_k >= 1
  )

  status <- if (length(severe) > 0L) {
    "fail"
  } else if (length(flagged) > 0L) {
    "review"
  } else {
    "pass"
  }

  pareto_table <- tryCatch(
    loo::pareto_k_table(raw),
    error = function(e) NULL
  )

  mcse <- tryCatch(
    loo::mcse_loo(raw),
    error = function(e) NA_real_
  )

  structure(
    list(
      status = status,
      raw = raw,
      pareto_k = pareto_k,
      flagged_observations = flagged,
      severe_observations = as.integer(severe),
      pareto_k_table = pareto_table,
      mcse_loo = mcse,
      source = source,
      automatic_selection = FALSE,
      interpretation = paste(
        "PSIS-LOO estimates out-of-sample predictive performance.",
        "Pareto-k diagnostics must be inspected before interpretation.",
        "No model is selected automatically."
      )
    ),
    class = "gp3bayes_psis_loo"
  )
}

#' Compute PSIS-LOO for a gp3bayes Fit
#'
#' @param fit A gp3bayes fit or `brmsfit`.
#' @param moment_match Whether to request moment matching.
#' @param reloo Whether to request exact refits for problematic observations.
#' @param cores Number of cores.
#' @param save_psis Whether to retain the PSIS object.
#'
#' @return A conservative `gp3bayes_psis_loo` result.
#' @export
compute_psis_loo <- function(
  fit,
  moment_match = FALSE,
  reloo = FALSE,
  cores = 1L,
  save_psis = TRUE
) {
  .gp3x_require("loo", "compute PSIS-LOO")
  .gp3x_require("brms", "compute PSIS-LOO for a brms fit")
  backend_fit <- .gp3x_unwrap_fit(fit)

  raw <- loo::loo(
    backend_fit,
    moment_match = moment_match,
    reloo = reloo,
    cores = cores,
    save_psis = save_psis
  )
  .gp3x_wrap_loo(raw, source = fit)
}

#' Compute PSIS-LOO from a Log-Likelihood Matrix
#'
#' This function supports deterministic tests and advanced workflows that
#' already possess pointwise log-likelihood draws.
#'
#' @param log_lik Matrix with posterior draws in rows and observations in
#'   columns.
#' @param chain_id Optional chain identifier for each row.
#' @inheritParams compute_psis_loo
#'
#' @return A `gp3bayes_psis_loo`.
#' @export
compute_psis_loo_from_log_lik <- function(
  log_lik,
  chain_id = NULL,
  cores = 1L,
  save_psis = TRUE
) {
  .gp3x_require("loo", "compute PSIS-LOO")
  if (!is.matrix(log_lik) || !is.numeric(log_lik) ||
      anyNA(log_lik) || any(!is.finite(log_lik))) {
    .gp3x_stop("`log_lik` must be a finite numeric matrix.")
  }

  r_eff <- NULL
  if (!is.null(chain_id)) {
    if (length(chain_id) != nrow(log_lik)) {
      .gp3x_stop("`chain_id` must have one value per log-likelihood row.")
    }
    r_eff <- loo::relative_eff(exp(log_lik), chain_id = chain_id)
  }

  raw <- loo::loo(
    log_lik,
    r_eff = r_eff,
    cores = cores,
    save_psis = save_psis
  )
  .gp3x_wrap_loo(raw, source = "log_likelihood_matrix")
}

#' Identify Influential PSIS-LOO Observations
#'
#' @param x A `gp3bayes_psis_loo` or raw loo object.
#' @param threshold Optional explicit Pareto-k threshold.
#' @param data Optional observation-level data to append.
#'
#' @return A data frame of flagged observations.
#' @export
identify_loo_influential_observations <- function(
  x,
  threshold = NULL,
  data = NULL
) {
  .gp3x_require("loo", "inspect Pareto-k diagnostics")
  raw <- if (inherits(x, "gp3bayes_psis_loo")) x$raw else x
  k <- loo::pareto_k_values(raw)
  influence <- loo::pareto_k_influence_values(raw)

  ids <- if (is.null(threshold)) {
    loo::pareto_k_ids(raw)
  } else {
    threshold <- .gp3x_scalar_number(threshold, "threshold")
    which(k >= threshold)
  }

  result <- data.frame(
    observation = as.integer(ids),
    pareto_k = k[ids],
    influence_pareto_k = influence[ids],
    severe = k[ids] >= 1,
    stringsAsFactors = FALSE
  )

  if (!is.null(data)) {
    if (!is.data.frame(data) || nrow(data) != length(k)) {
      .gp3x_stop(
        "`data` must have one row per PSIS-LOO observation."
      )
    }
    result <- cbind(result, data[ids, , drop = FALSE])
  }
  result
}

#' Compare Models with PSIS-LOO
#'
#' @param models Named list of gp3bayes fits, `brmsfit` objects, or
#'   `gp3bayes_psis_loo` objects.
#' @inheritParams compute_psis_loo
#'
#' @return A `gp3bayes_loo_comparison`. The result never selects a model.
#' @export
compare_psis_loo <- function(
  models,
  moment_match = FALSE,
  reloo = FALSE,
  cores = 1L
) {
  .gp3x_require("loo", "compare PSIS-LOO results")
  if (!is.list(models) || length(models) < 2L) {
    .gp3x_stop("`models` must be a list containing at least two models.")
  }
  if (is.null(names(models)) || any(!nzchar(names(models))) ||
      anyDuplicated(names(models))) {
    .gp3x_stop("`models` must have unique non-empty names.")
  }

  wrapped <- lapply(
    models,
    function(model) {
      if (inherits(model, "gp3bayes_psis_loo")) {
        model
      } else {
        compute_psis_loo(
          model,
          moment_match = moment_match,
          reloo = reloo,
          cores = cores
        )
      }
    }
  )

  observation_counts <- vapply(
    wrapped,
    function(x) nrow(x$raw$pointwise),
    integer(1L)
  )
  if (length(unique(observation_counts)) != 1L) {
    .gp3x_stop(
      "All models must contain the same number of pointwise observations."
    )
  }

  raw_list <- lapply(wrapped, `[[`, "raw")
  comparison <- loo::loo_compare(raw_list)
  any_problem <- any(vapply(
    wrapped,
    function(x) x$status != "pass",
    logical(1L)
  ))

  structure(
    list(
      status = if (any_problem) "review" else "review",
      comparison = comparison,
      loo = wrapped,
      automatic_selection = FALSE,
      interpretation = paste(
        "ELPD differences and uncertainty are descriptive.",
        "No model is automatically selected."
      )
    ),
    class = "gp3bayes_loo_comparison"
  )
}

#' Compute LOO Model-Averaging Weights
#'
#' @param x A `gp3bayes_loo_comparison` or named list of PSIS-LOO objects.
#' @param method Either stacking or pseudo-BMA.
#' @param cores Number of cores.
#'
#' @return A `gp3bayes_loo_weights` object.
#' @export
compute_loo_model_weights <- function(
  x,
  method = c("stacking", "pseudobma"),
  cores = 1L
) {
  .gp3x_require("loo", "compute LOO model weights")
  method <- match.arg(method)

  loo_list <- if (inherits(x, "gp3bayes_loo_comparison")) {
    lapply(x$loo, `[[`, "raw")
  } else if (is.list(x)) {
    lapply(
      x,
      function(item) {
        if (inherits(item, "gp3bayes_psis_loo")) item$raw else item
      }
    )
  } else {
    .gp3x_stop(
      "`x` must be a LOO comparison or a list of LOO objects."
    )
  }

  weights <- loo::loo_model_weights(
    loo_list,
    method = method,
    cores = cores
  )

  structure(
    list(
      method = method,
      weights = weights,
      automatic_selection = FALSE,
      interpretation = paste(
        "Weights combine predictive distributions.",
        "They are not evidence that a single model is substantively correct."
      )
    ),
    class = "gp3bayes_loo_weights"
  )
}

#' @export
print.gp3bayes_psis_loo <- function(x, ...) {
  cat("\nPSIS-LOO audit\n")
  cat(" Status: ", x$status, "\n", sep = "")
  print(x$raw)
  cat(
    " Flagged observations: ",
    length(x$flagged_observations),
    "\n",
    sep = ""
  )
  cat(
    " Severe observations (k >= 1): ",
    length(x$severe_observations),
    "\n",
    sep = ""
  )
  cat(" Automatic model selection: FALSE\n")
  invisible(x)
}

#' @export
plot.gp3bayes_psis_loo <- function(x, diagnostic = "k", ...) {
  plot(x$raw, diagnostic = diagnostic, ...)
  invisible(x)
}

#' @export
print.gp3bayes_loo_comparison <- function(x, ...) {
  cat("\nPSIS-LOO comparison\n")
  print(x$comparison)
  cat("\nAutomatic model selection: FALSE\n")
  cat(x$interpretation, "\n")
  invisible(x)
}

#' @export
print.gp3bayes_loo_weights <- function(x, ...) {
  cat("\nLOO model weights\n")
  cat(" Method: ", x$method, "\n", sep = "")
  print(x$weights)
  cat("\nAutomatic model selection: FALSE\n")
  invisible(x)
}

#' Assess Power-Scaled Prior and Likelihood Sensitivity
#'
#' Delegates to priorsense while retaining a conservative review status.
#' Low local sensitivity does not prove that prior choices are irrelevant or
#' that a model is robust.
#'
#' @param fit A gp3bayes fit or `brmsfit`.
#' @param variable Optional posterior variables to inspect.
#' @param prior_selection Optional tagged priors to perturb.
#' @param likelihood_selection Optional likelihood subset.
#'
#' @return A `gp3bayes_powerscale_sensitivity`.
#' @export
assess_powerscaled_sensitivity <- function(
  fit,
  variable = NULL,
  prior_selection = NULL,
  likelihood_selection = NULL
) {
  .gp3x_require("priorsense", "assess power-scaled sensitivity")
  backend_fit <- .gp3x_unwrap_fit(fit)

  args <- list(
    x = backend_fit,
    variable = variable,
    prior_selection = prior_selection,
    likelihood_selection = likelihood_selection
  )
  args <- args[!vapply(args, is.null, logical(1L))]

  raw <- tryCatch(
    do.call(priorsense::powerscale_sensitivity, args),
    error = function(e) {
      .gp3x_stop(
        "Power-scaling sensitivity failed: ",
        conditionMessage(e),
        " Refit with `fit_*_model_backend()` so that all required ",
        "parameters are saved."
      )
    }
  )

  diagnosis <- tryCatch(
    {
      table <- as.data.frame(raw)
      if ("diagnosis" %in% names(table)) unique(table$diagnosis) else character()
    },
    error = function(e) character()
  )

  structure(
    list(
      status = "review",
      raw = raw,
      fit = fit,
      variable = variable,
      prior_selection = prior_selection,
      likelihood_selection = likelihood_selection,
      diagnoses = diagnosis,
      robustness_established = FALSE,
      interpretation = paste(
        "Power-scaling is a local sensitivity diagnostic.",
        "It does not establish universal robustness."
      )
    ),
    class = "gp3bayes_powerscale_sensitivity"
  )
}

#' Create a Power-Scaling Sequence
#'
#' @inheritParams assess_powerscaled_sensitivity
#' @param component Either prior, likelihood, or both, as supported by
#'   priorsense.
#'
#' @return A priorsense powerscaled sequence.
#' @export
powerscale_sequence_for_fit <- function(
  fit,
  variable = NULL,
  prior_selection = NULL,
  likelihood_selection = NULL,
  component = "both"
) {
  .gp3x_require("priorsense", "create a power-scaling sequence")
  backend_fit <- .gp3x_unwrap_fit(fit)
  args <- list(
    x = backend_fit,
    variable = variable,
    prior_selection = prior_selection,
    likelihood_selection = likelihood_selection,
    component = component
  )
  args <- args[!vapply(args, is.null, logical(1L))]
  do.call(priorsense::powerscale_sequence, args)
}

#' @export
print.gp3bayes_powerscale_sensitivity <- function(x, ...) {
  cat("\nPower-scaled sensitivity audit\n")
  cat(" Status: review\n")
  print(x$raw)
  cat("\nRobustness established: FALSE\n")
  cat(x$interpretation, "\n")
  invisible(x)
}

#' @export
plot.gp3bayes_powerscale_sensitivity <- function(
  x,
  type = c("ecdf", "density", "quantities"),
  quantity = c("mean", "sd"),
  ...
) {
  .gp3x_require("priorsense", "plot power-scaled sensitivity")
  type <- match.arg(type)
  backend_fit <- .gp3x_unwrap_fit(x$fit)

  common <- list(
    x = backend_fit,
    variable = x$variable,
    prior_selection = x$prior_selection,
    likelihood_selection = x$likelihood_selection
  )
  common <- common[!vapply(common, is.null, logical(1L))]
  common <- c(common, list(...))

  if (identical(type, "density")) {
    return(do.call(priorsense::powerscale_plot_dens, common))
  }
  if (identical(type, "ecdf")) {
    return(do.call(priorsense::powerscale_plot_ecdf, common))
  }
  common$quantity <- quantity
  do.call(priorsense::powerscale_plot_quantities, common)
}

#' Simulate a Dedicated Binary Pathology Scenario
#'
#' @param scenario Pathological or stress-test scenario.
#' @param seed Non-negative integer seed.
#'
#' @return A `gp3bayes_pathological_simulation`.
#' @export
simulate_binary_pathology <- function(
  scenario = c(
    "null_contrast",
    "weak_information",
    "severe_imbalance",
    "near_separation",
    "omitted_random_slope",
    "sparse_item_structure",
    "all_zero_participants",
    "rank_deficiency",
    "missing_outcomes"
  ),
  seed = 1L
) {
  scenario <- match.arg(scenario)
  seed <- .gp3x_scalar_integer(seed, "seed", 0L)

  args <- list(
    n_participants = 30L,
    trials_per_participant = 12L,
    n_items = 12L,
    condition_effect = 0.8,
    random_slope_sd = 0.3,
    balanced_condition = TRUE,
    condition_probability = 0.5,
    seed = seed
  )

  if (scenario == "null_contrast") {
    args$condition_effect <- 0
  } else if (scenario == "weak_information") {
    args$n_participants <- 8L
    args$trials_per_participant <- 4L
    args$n_items <- 4L
    args$random_slope_sd <- 0
  } else if (scenario == "severe_imbalance") {
    args$balanced_condition <- FALSE
    args$condition_probability <- 0.95
  } else if (scenario == "near_separation") {
    args$intercept <- -4
    args$condition_effect <- 8
    args$random_slope_sd <- 0
  } else if (scenario == "omitted_random_slope") {
    args$random_slope_sd <- 1
  } else if (scenario == "sparse_item_structure") {
    args$n_items <- 2L
  }

  simulation <- do.call(simulate_hierarchical_binary_data, args)
  data <- simulation$data

  if (scenario == "all_zero_participants") {
    ids <- unique(data$participant_id)[1:2]
    data$selected[data$participant_id %in% ids] <- 0L
  } else if (scenario == "rank_deficiency") {
    data$duplicate_trial_covariate <- data$trial_covariate
  } else if (scenario == "missing_outcomes") {
    set.seed(seed + 1L)
    data$selected[sample.int(nrow(data), max(1L, floor(0.1 * nrow(data))))] <- NA
  }

  expected <- switch(
    scenario,
    null_contrast = "pass_or_review",
    weak_information = "review",
    severe_imbalance = "review_or_fail",
    near_separation = "review",
    omitted_random_slope = "review",
    sparse_item_structure = "review",
    all_zero_participants = "review_or_fail",
    rank_deficiency = "fail",
    missing_outcomes = "fail"
  )

  structure(
    list(
      family = "binary",
      scenario = scenario,
      data = data,
      truth = simulation$truth,
      design = simulation$design,
      expected_gate = expected,
      seed = seed,
      source_simulation = simulation,
      interpretation = paste(
        "This scenario is a deliberate stress or failure case.",
        "A passed structural audit would not establish model adequacy."
      )
    ),
    class = "gp3bayes_pathological_simulation"
  )
}

#' Simulate a Dedicated Duration Pathology Scenario
#'
#' @param scenario Pathological or stress-test duration scenario.
#' @inheritParams simulate_binary_pathology
#'
#' @return A `gp3bayes_pathological_simulation`.
#' @export
simulate_duration_pathology <- function(
  scenario = c(
    "null_ratio",
    "high_group_heterogeneity",
    "weak_information",
    "severe_imbalance",
    "heavy_tailed_contamination",
    "mixture",
    "censoring",
    "incorrect_unit",
    "zero_duration",
    "negative_duration"
  ),
  seed = 1L
) {
  scenario <- match.arg(scenario)
  seed <- .gp3x_scalar_integer(seed, "seed", 0L)

  args <- list(
    n_participants = 30L,
    trials_per_participant = 12L,
    n_items = 12L,
    condition_effect = log(1.15),
    participant_sd = 0.35,
    item_sd = 0.20,
    residual_sd = 0.40,
    balanced_condition = TRUE,
    condition_probability = 0.5,
    outcome_unit = "milliseconds",
    seed = seed
  )

  if (scenario == "null_ratio") {
    args$condition_effect <- 0
  } else if (scenario == "high_group_heterogeneity") {
    args$participant_sd <- 1.0
    args$item_sd <- 0.7
  } else if (scenario == "weak_information") {
    args$n_participants <- 8L
    args$trials_per_participant <- 4L
    args$n_items <- 4L
  } else if (scenario == "severe_imbalance") {
    args$balanced_condition <- FALSE
    args$condition_probability <- 0.95
  }

  simulation <- do.call(simulate_hierarchical_duration_data, args)
  data <- simulation$data

  if (scenario == "heavy_tailed_contamination") {
    set.seed(seed + 1L)
    ids <- sample.int(nrow(data), max(2L, floor(0.05 * nrow(data))))
    data$duration[ids] <- data$duration[ids] * exp(stats::rt(length(ids), 2))
  } else if (scenario == "mixture") {
    set.seed(seed + 1L)
    group <- stats::rbinom(nrow(data), 1L, 0.25)
    data$duration <- data$duration * ifelse(group == 1L, 3.5, 1)
    data$mixture_component <- group
  } else if (scenario == "censoring") {
    deadline <- stats::quantile(data$duration, 0.85)
    data$censored <- data$duration >= deadline
    data$duration <- pmin(data$duration, deadline)
  } else if (scenario == "incorrect_unit") {
    data$duration <- data$duration / 1000
    simulation$truth$outcome_unit <- "milliseconds_declared_but_seconds_stored"
  } else if (scenario == "zero_duration") {
    data$duration[[1L]] <- 0
  } else if (scenario == "negative_duration") {
    data$duration[[1L]] <- -abs(data$duration[[1L]])
  }

  expected <- switch(
    scenario,
    null_ratio = "pass_or_review",
    high_group_heterogeneity = "review",
    weak_information = "review",
    severe_imbalance = "review_or_fail",
    heavy_tailed_contamination = "review_or_fail",
    mixture = "fail_adequacy",
    censoring = "fail_contract",
    incorrect_unit = "fail_contract",
    zero_duration = "fail",
    negative_duration = "fail"
  )

  structure(
    list(
      family = "duration",
      scenario = scenario,
      data = data,
      truth = simulation$truth,
      design = simulation$design,
      expected_gate = expected,
      seed = seed,
      source_simulation = simulation,
      interpretation = paste(
        "This scenario is a deliberate stress or failure case.",
        "Extreme values are not automatically deleted."
      )
    ),
    class = "gp3bayes_pathological_simulation"
  )
}

#' Evaluate a Pathological Simulation Against the Contract Gate
#'
#' @param x A `gp3bayes_pathological_simulation`.
#'
#' @return A `gp3bayes_pathology_evaluation`.
#' @export
evaluate_pathological_simulation <- function(x) {
  if (!inherits(x, "gp3bayes_pathological_simulation")) {
    .gp3x_stop("`x` must be a pathological simulation.")
  }

  semantic_failure <- FALSE
  semantic_reason <- NA_character_

  if (x$family == "duration" && x$scenario == "censoring") {
    semantic_failure <- TRUE
    semantic_reason <- "Censored observations violate the uncensored contract."
  }
  if (x$family == "duration" && x$scenario == "incorrect_unit") {
    semantic_failure <- TRUE
    semantic_reason <- "The stored values and declared measurement unit disagree."
  }

  prepared <- NULL
  error_message <- NULL

  if (!semantic_failure) {
    attempt <- tryCatch(
      {
        predictors <- c("participant_covariate", "trial_covariate")
        if (x$family == "binary" && x$scenario == "rank_deficiency") {
          predictors <- c(predictors, "duplicate_trial_covariate")
        }

        contract <- create_model_contract(
          family = x$family,
          outcome_col = if (x$family == "binary") "selected" else "duration",
          participant_col = "participant_id",
          item_col = "item_id",
          trial_col = "trial_id",
          condition_col = "condition",
          predictors = predictors,
          interaction = c("condition", "participant_covariate"),
          random_slope = !identical(x$scenario, "omitted_random_slope"),
          outcome_unit = if (x$family == "duration") "milliseconds" else NULL
        )

        if (x$family == "binary") {
          prepare_hierarchical_binary_data(
            data = x$data,
            contract = contract,
            condition_levels = c("control", "treatment"),
            missing = "error"
          )
        } else {
          prepare_hierarchical_duration_data(
            data = x$data,
            contract = contract,
            condition_levels = c("control", "treatment"),
            missing = "error"
          )
        }
      },
      error = function(e) e
    )

    if (inherits(attempt, "error")) {
      error_message <- conditionMessage(attempt)
    } else {
      prepared <- attempt
    }
  } else {
    error_message <- semantic_reason
  }

  actual_status <- if (!is.null(error_message)) "fail" else "pass"

  structure(
    list(
      family = x$family,
      scenario = x$scenario,
      expected_gate = x$expected_gate,
      actual_structural_status = actual_status,
      error = error_message,
      prepared = prepared,
      semantic_failure = semantic_failure,
      interpretation = paste(
        "Structural status is not a posterior adequacy decision.",
        "Review the expected failure mechanism and diagnostic context."
      )
    ),
    class = "gp3bayes_pathology_evaluation"
  )
}

#' @export
print.gp3bayes_pathological_simulation <- function(x, ...) {
  cat("\nPathological simulation\n")
  cat(" Family: ", x$family, "\n", sep = "")
  cat(" Scenario: ", x$scenario, "\n", sep = "")
  cat(" Rows: ", nrow(x$data), "\n", sep = "")
  cat(" Expected gate: ", x$expected_gate, "\n", sep = "")
  cat(x$interpretation, "\n")
  invisible(x)
}

#' @export
plot.gp3bayes_pathological_simulation <- function(x, ...) {
  if (x$family == "binary") {
    rates <- tapply(x$data$selected, x$data$participant_id, mean, na.rm = TRUE)
    graphics::hist(
      rates,
      xlab = "Participant event rate",
      main = paste("Binary pathology:", x$scenario),
      ...
    )
  } else {
    graphics::hist(
      log(pmax(x$data$duration, .Machine$double.eps)),
      xlab = "Log duration",
      main = paste("Duration pathology:", x$scenario),
      ...
    )
  }
  invisible(x)
}

#' @export
print.gp3bayes_pathology_evaluation <- function(x, ...) {
  cat("\nPathology evaluation\n")
  cat(" Family: ", x$family, "\n", sep = "")
  cat(" Scenario: ", x$scenario, "\n", sep = "")
  cat(" Expected gate: ", x$expected_gate, "\n", sep = "")
  cat(" Structural status: ", x$actual_structural_status, "\n", sep = "")
  if (!is.null(x$error)) {
    cat(" Reason: ", x$error, "\n", sep = "")
  }
  cat(x$interpretation, "\n")
  invisible(x)
}

#' Create a brms-Based Simulation-Based Calibration Plan
#'
#' Constructs a complete SBC generator/backend pair using the restricted
#' gp3bayes brms translation. Because the generator and backend share brms
#' implementation code, this plan is mainly a computational-calibration check;
#' custom independent generators remain preferable for detecting shared
#' implementation errors.
#'
#' @param specification An approved binary or duration specification.
#' @param n_sims Number of simulated datasets.
#' @param backend Either rstan or cmdstanr.
#' @param chains Number of chains used per SBC fit.
#' @param iter Total iterations per SBC fit.
#' @param warmup Warmup iterations.
#' @param thin Thinning interval.
#' @param seed Seed used when datasets are generated.
#' @param generator_iter Total prior-only generator iterations.
#' @param generator_warmup Prior-only generator warmup.
#'
#' @return A `gp3bayes_sbc_plan`.
#' @export
create_brms_sbc_plan <- function(
  specification,
  n_sims = 20L,
  backend = c("rstan", "cmdstanr"),
  chains = 2L,
  iter = 1000L,
  warmup = 500L,
  thin = 1L,
  seed = 1L,
  generator_iter = 3000L,
  generator_warmup = 2000L
) {
  .gp3x_require("SBC", "create a simulation-based calibration plan")
  .gp3x_require("brms", "create a brms SBC generator")
  backend <- match.arg(backend)

  if (backend == "rstan") {
    .gp3x_require("rstan", "use the rstan SBC backend")
  } else {
    check_cmdstan_backend(strict = TRUE)
  }

  n_sims <- .gp3x_scalar_integer(n_sims, "n_sims", 1L)
  chains <- .gp3x_scalar_integer(chains, "chains", 1L)
  iter <- .gp3x_scalar_integer(iter, "iter", 100L)
  warmup <- .gp3x_scalar_integer(warmup, "warmup", 0L)
  thin <- .gp3x_scalar_integer(thin, "thin", 1L)
  seed <- .gp3x_scalar_integer(seed, "seed", 0L)
  generator_iter <- .gp3x_scalar_integer(
    generator_iter, "generator_iter", 100L
  )
  generator_warmup <- .gp3x_scalar_integer(
    generator_warmup, "generator_warmup", 0L
  )

  if (warmup >= iter || generator_warmup >= generator_iter) {
    .gp3x_stop("Warmup must be smaller than total iterations.")
  }

  translation <- .gp3x_translate_for_backend(specification)

  generator <- SBC::SBC_generator_brms(
    formula = translation$formula,
    data = specification$prepared$data,
    family = translation$family_object,
    prior = translation$priors,
    backend = backend,
    algorithm = "sampling",
    chains = 1L,
    iter = generator_iter,
    warmup = generator_warmup,
    thin = max(
      1L,
      floor((generator_iter - generator_warmup) / n_sims)
    ),
    generate_lp = TRUE,

    # SBC 0.5.0.9000 uses brms::log_lik() in its chunked branch but an
    # unqualified log_lik() call in its serial branch. A chunk size of one
    # keeps likelihood generation namespace-safe for n_sims >= 2.
    generate_lp_chunksize = 1L,

    refresh = 0
  )

  inference_backend <- SBC::SBC_backend_brms_from_generator(
    generator,
    chains = chains,
    iter = iter,
    warmup = warmup,
    thin = thin,
    algorithm = "sampling",
    refresh = 0
  )

  structure(
    list(
      plan_version = "0.2",
      family = specification$family,
      specification = specification,
      translation = translation,
      generator = generator,
      inference_backend = inference_backend,
      n_sims = n_sims,
      backend = backend,
      seed = seed,
      shared_implementation = TRUE,
      interpretation = paste(
        "The brms generator and brms backend share implementation code.",
        "Use an independently coded generator for stronger implementation validation."
      )
    ),
    class = "gp3bayes_sbc_plan"
  )
}

#' Create an Expert Custom SBC Plan
#'
#' Wraps an independently coded generator function and a user-supplied SBC
#' backend. The generator must return `variables` and `generated` elements as
#' required by SBC.
#'
#' @param generator_function Function producing one SBC dataset.
#' @param backend A valid SBC backend object.
#' @param n_sims Number of datasets.
#' @param generator_args Named list passed to the generator constructor.
#' @param seed Seed used for dataset generation.
#'
#' @return A `gp3bayes_sbc_plan`.
#' @export
create_custom_sbc_plan <- function(
  generator_function,
  backend,
  n_sims = 20L,
  generator_args = list(),
  seed = 1L
) {
  .gp3x_require("SBC", "create a custom simulation-based calibration plan")
  if (!is.function(generator_function)) {
    .gp3x_stop("`generator_function` must be a function.")
  }
  if (!is.list(generator_args) || is.null(names(generator_args)) &&
      length(generator_args) > 0L) {
    .gp3x_stop("`generator_args` must be a named list.")
  }

  n_sims <- .gp3x_scalar_integer(n_sims, "n_sims", 2L)
  seed <- .gp3x_scalar_integer(seed, "seed", 0L)

  generator <- do.call(
    SBC::SBC_generator_function,
    c(list(f = generator_function), generator_args)
  )

  structure(
    list(
      plan_version = "0.2",
      family = "custom",
      specification = NULL,
      translation = NULL,
      generator = generator,
      inference_backend = backend,
      n_sims = n_sims,
      backend = class(backend)[[1L]],
      seed = seed,
      shared_implementation = FALSE,
      interpretation = paste(
        "The generator is independently supplied.",
        "Calibration still depends on adequate simulation count and diagnostics."
      )
    ),
    class = "gp3bayes_sbc_plan"
  )
}

#' Run a Simulation-Based Calibration Plan
#'
#' @param plan A `gp3bayes_sbc_plan`.
#' @param cores_per_fit Cores used by each fit.
#' @param keep_fits Whether to retain fitted objects.
#' @param thin_ranks Optional rank thinning.
#' @param cache_mode SBC cache mode.
#' @param cache_location Optional cache location.
#'
#' @return A `gp3bayes_sbc_result`.
#' @export
run_sbc_plan <- function(
  plan,
  cores_per_fit = 1L,
  keep_fits = FALSE,
  thin_ranks = NULL,
  cache_mode = "none",
  cache_location = NULL
) {
  .gp3x_require("SBC", "run simulation-based calibration")
  if (!inherits(plan, "gp3bayes_sbc_plan")) {
    .gp3x_stop("`plan` must be a gp3bayes SBC plan.")
  }

  set.seed(plan$seed)
  datasets <- SBC::generate_datasets(
    plan$generator,
    n_sims = plan$n_sims
  )

  args <- list(
    datasets = datasets,
    backend = plan$inference_backend,
    cores_per_fit = cores_per_fit,
    keep_fits = keep_fits,
    cache_mode = cache_mode,
    cache_location = cache_location
  )
  if (!is.null(thin_ranks)) {
    args$thin_ranks <- thin_ranks
  }
  args <- args[!vapply(args, is.null, logical(1L))]

  raw <- do.call(SBC::compute_SBC, args)

  diagnostics_ok <- tryCatch(
    {
      diagnostic_columns <- grep(
        "diagnostic|error|warning",
        names(raw$stats),
        ignore.case = TRUE,
        value = TRUE
      )
      if (length(diagnostic_columns) == 0L) {
        NA
      } else {
        TRUE
      }
    },
    error = function(e) NA
  )

  status <- if (plan$n_sims < 20L) "review" else "review"

  structure(
    list(
      status = status,
      plan = plan,
      datasets = datasets,
      raw = raw,
      diagnostics_inspected = diagnostics_ok,
      calibration_established = FALSE,
      interpretation = paste(
        "SBC results require graphical and diagnostic review.",
        "Absence of detected failures does not prove implementation correctness."
      )
    ),
    class = "gp3bayes_sbc_result"
  )
}

#' Summarise an SBC Result
#'
#' @param x A `gp3bayes_sbc_result`.
#'
#' @return A conservative summary list.
#' @export
summarise_sbc_result <- function(x) {
  if (!inherits(x, "gp3bayes_sbc_result")) {
    .gp3x_stop("`x` must be a gp3bayes SBC result.")
  }
  list(
    status = x$status,
    family = x$plan$family,
    backend = x$plan$backend,
    simulations = x$plan$n_sims,
    shared_implementation = x$plan$shared_implementation,
    calibration_established = FALSE,
    stats = x$raw$stats,
    interpretation = x$interpretation
  )
}

#' @export
print.gp3bayes_sbc_plan <- function(x, ...) {
  cat("\nSimulation-based calibration plan\n")
  cat(" Family: ", x$family, "\n", sep = "")
  cat(" Backend: ", x$backend, "\n", sep = "")
  cat(" Simulations: ", x$n_sims, "\n", sep = "")
  cat(" Shared generator/backend implementation: ",
      x$shared_implementation, "\n", sep = "")
  cat(x$interpretation, "\n")
  invisible(x)
}

#' @export
print.gp3bayes_sbc_result <- function(x, ...) {
  cat("\nSimulation-based calibration result\n")
  cat(" Status: ", x$status, "\n", sep = "")
  cat(" Simulations: ", x$plan$n_sims, "\n", sep = "")
  cat(" Calibration established: FALSE\n")
  print(x$raw)
  cat(x$interpretation, "\n")
  invisible(x)
}

#' @export
plot.gp3bayes_sbc_result <- function(
  x,
  type = c("rank", "ecdf", "coverage", "simulated_vs_estimated"),
  ...
) {
  .gp3x_require("SBC", "plot simulation-based calibration results")
  type <- match.arg(type)
  if (type == "rank") {
    return(SBC::plot_rank_hist(x$raw, ...))
  }
  if (type == "ecdf") {
    return(SBC::plot_ecdf_diff(x$raw, ...))
  }
  if (type == "coverage") {
    return(SBC::plot_coverage(x$raw, ...))
  }
  SBC::plot_sim_estimated(x$raw, ...)
}
